[package]
name = "find-all-anagrams-in-a-string"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "find_all_anagrams_in_a_string"
path = "lib.rs"
