[package]
name = "valid-parentheses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "valid_parentheses"
path = "lib.rs"
