[package]
name = "boats-to-save-people"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "boats_to_save_people"
path = "lib.rs"
