[workspace]

members = [
    "problems/0002-add-two-numbers",
    "problems/0003-longest-substring-without-repeating-characters",
    "problems/0005-longest-palindromic-substring",
    "problems/0011-container-with-most-water",
    "problems/0015-3sum",
    "problems/0017-letter-combinations-of-a-phone-number",
    "problems/0019-remove-nth-node-from-end-of-list",
    "problems/0022-generate-parentheses",
]
