[workspace]

members = [
    "problems/0002-add-two-numbers",
    "problems/0003-longest-substring-without-repeating-characters",
    "problems/0005-longest-palindromic-substring",
    "problems/0011-container-with-most-water",
    "problems/0015-3sum",
    "problems/0017-letter-combinations-of-a-phone-number",
    "problems/0019-remove-nth-node-from-end-of-list",
    "problems/0022-generate-parentheses",
    "problems/0031-next-permutation",
    "problems/0033-search-in-rotated-sorted-array",
    "problems/0034-find-first-and-last-position-of-element-in-sorted-array",
    "problems/0039-combination-sum",
    "problems/0046-permutations",
    "problems/0048-rotate-image",
    "problems/0049-group-anagrams",
    "problems/0055-jump-game",
]
