[package]
name = "all-paths-from-source-to-target"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "all_paths_from_source_to_target"
path = "lib.rs"
