[package]
name = "april-leetcoding-challenge-2021_week-2_3707"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../../../../utils" }

[lib]
name = "week2_3707"
path = "lib.rs"
