[package]
name = "may-leetcoding-challenge-2021_week-2_3740"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "week2_3740"
path = "lib.rs"
