[package]
name = "minimize-deviation-in-array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "minimize_deviation_in_array"
path = "lib.rs"
