[package]
name = "single-element-in-a-sorted-array"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "single_element_in_a_sorted_array"
path = "lib.rs"
