[package]
name = "maximum-width-of-binary-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../../utils" }

[lib]
name = "maximum_width_of_binary_tree"
path = "lib.rs"
