[package]
name = "maximum-frequency-stack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "maximum_frequency_stack"
path = "lib.rs"
