[package]
name = "30-day-leetcoding-challenge_week-1_3285"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "week1_3285"
path = "lib.rs"
