[package]
name = "split-array-largest-sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "split_array_largest_sum"
path = "lib.rs"
