[package]
name = "august-leetcoding-challenge_week-1_3414"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "week1_3414"
path = "lib.rs"
