[package]
name = "march-leetcoding-challenge-2021_week-5_3690"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "week5_3690"
path = "lib.rs"
