[package]
name = "april-leetcoding-challenge-2021_week-3_3709"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "week3_3709"
path = "lib.rs"
