[package]
name = "november-leetcoding-challenge_week-4_3541"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../../../../utils" }

[lib]
name = "week4_3541"
path = "lib.rs"
