[package]
name = "august-leetcoding-challenge-2021_week-1_3837"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "week1_3837"
path = "lib.rs"
