[package]
name = "may-leetcoding-challenge_week-4_3337"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "week4_3337"
path = "lib.rs"
