[package]
name = "rectangle-area"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust_lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "rectangle_area"
path = "lib.rs"
