[package]
name = "score-of-parentheses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "score_of_parentheses"
path = "lib.rs"
