[package]
name = "march-leetcoding-challenge-2021_week-3_3675"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[lib]
name = "week3_3675"
path = "lib.rs"
