[package]
name = "august-leetcoding-challenge_week-4_3433"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[lib]
name = "week4_3433"
path = "lib.rs"
